package sec2;
//UserExceptino : 사용자 정의 예외처리
public class UserException {
	public static void main(String[] args) {
		try {
			method1();
		} catch (RunException e) {
			e.printStackTrace();
		}
	}
	public static void method1() throws RunException {
		throw new RunException("사용자 예외");
	}
}
